[tool.poetry]
name = "utilities"
version = "0.0.1"
description = "Nemesis Utilities"
authors = ["Nemesis Team"]

[tool.poetry.dependencies]
python = "^3.10"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"