version: '3.7'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    container_name: redis-nemesis-test

  test:
    build:
      dockerfile: ./Dockerfile
      context: .
    volumes:
      - .:/app
    environment:
      - NEMESIS_CONFIG=$c
      - DEBUG=$d
      - REDIS_CONTAINER_NAME=redis-nemesis-test
    depends_on:
      - redis
    user: root
    command: [ "pytest", "/app/tests" ]