version: '3.7'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    container_name: redis-nemesis-dev

  dev:
    privileged: true
    build:
      dockerfile: ./Dockerfile
      context: .
    volumes:
      - .:/app
    environment:
      - NEMESIS_CONFIG=$c
      - DEBUG=$d
      - REDIS_CONTAINER_NAME=redis-nemesis-dev
    depends_on:
      - redis
    command: [ "python3", "/app/src/manager.py"]
