version: '3.7'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    container_name: redis-nemesis-prod

  prod:
    build:
      dockerfile: ./Dockerfile
      context: .
    environment:
        - NEMESIS_CONFIG=$c
        - DEBUG=$d
        - REDIS_CONTAINER_NAME=redis-nemesis-prod
    depends_on:
      - redis
    command: [ "python3", "/app/src/manager.py" ]
    devices:
      - "/dev/i2c-1:/dev/i2c-1"