version: '3.7'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    container_name: redis-ipc
    networks:
      - ipc

  # ---------------------------------------------------------
  # Prod: basic image with no code reloading
  # Dev: same but used code is located in a bound volume
  # ---------------------------------------------------------
  prod:
    build:
      dockerfile: ./Dockerfile
    environment:
        - NEMESIS_CONFIG=$c
        - DEBUG=$d
    networks:
      - ipc
    depends_on:
      - redis
    command: [ "python3", "/app/src/manager.py" ]

  dev:
    build:
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    environment:
      - NEMESIS_CONFIG=$c
      - DEBUG=$d
    networks:
      - ipc
    depends_on:
      - redis
    command: [ "python3", "/app/src/manager.py" ]

networks:
    ipc:
        driver: bridge