version: '3.7'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    container_name: redis-ipc

  # ---------------------------------------------------------
  # Prod: basic image with no code reloading
  # Dev: same but used code is located in a bound volume
  # Test: same as dev but runs pytest instead of manager.py
  # ---------------------------------------------------------
  prod:
    build:
      dockerfile: ./Dockerfile
      context: .
    environment:
        - NEMESIS_CONFIG=$c
        - DEBUG=$d
    depends_on:
      - redis
    command: [ "python3", "/app/src/manager.py" ]

  dev:
    build:
      dockerfile: ./Dockerfile
      context: .
    volumes:
      - .:/app
    environment:
      - NEMESIS_CONFIG=$c
      - DEBUG=$d
    depends_on:
      - redis
    command: [ "python3", "/app/src/manager.py" ]

  test:
    build:
      dockerfile: ./Dockerfile
      context: .
    volumes:
      - .:/app
    environment:
      - NEMESIS_CONFIG=$c
      - DEBUG=$d
    depends_on:
      - redis
    user: root
    command: [ "pytest", "/app/tests" ]