# ----------------------------------------------------------------------------------------------------------------------
#                                     NEMESIS AIR EMBEDDED SYSTEMS ENVIRONMENT
# ----------------------------------------------------------------------------------------------------------------------
FROM python:3.11-slim-bullseye
USER root

RUN pip install matplotlib

# CMD defined in compose.yml
CMD []
ENTRYPOINT []
